const dictionary: Record<string, string> = {
  // Technology
  "technology": "ٹیکنالوجی",
  "internet": "انٹرنیٹ",
  "world": "دنیا",
  "future": "مستقبل",
  "AI": "مصنوعی ذہانت",
  "computer": "کمپیوٹر",
  "mobile": "موبائل",
  "device": "ڈیوائس",
  "software": "سافٹ ویئر",
  "hardware": "ہارڈ ویئر",
  "data": "ڈیٹا",
  "cloud": "کلاؤڈ",
  "digital": "ڈیجیٹل",
  "virtual": "ورچوئل",
  "network": "نیٹ ورک",

  // General
  "information": "معلومات",
  "knowledge": "علم",
  "system": "نظام",
  "service": "سروس",
  "solution": "حل",
  "development": "ترقی",
  "progress": "ترقی",
  "change": "تبدیلی",
  "innovation": "اختراع",
  "trend": "رجحان",
  "global": "عالمی",
  "local": "مقامی",
  "modern": "جدید",
  "traditional": "روایتی",
  "quality": "معیار",

  // Blogging
  "article": "مضمون",
  "blog": "بلاگ",
  "content": "مواد",
  "writer": "مصنف",
  "reader": "قاری",
  "comment": "تبصرہ",
  "share": "شیئر",
  "like": "لائک",
  "follow": "فالو",
  "subscribe": "سبسکرائب",
  "update": "اپ ڈیٹ",
  "news": "خبریں",
  "trending": "مقبول",
  "popular": "مقبول",
  "viral": "وائرل",

  // Time
  "time": "وقت",
  "minute": "منٹ",
  "hour": "گھنٹہ",
  "day": "دن",
  "week": "ہفتہ",
  "month": "مہینہ",
  "year": "سال",
  "today": "آج",
  "tomorrow": "کل",
  "yesterday": "کل",
  "now": "اب",
  "soon": "جلد",
  "early": "جلدی",
  "late": "دیر",

  // Business
  "business": "کاروبار",
  "market": "مارکیٹ",
  "product": "پروڈکٹ",
  "price": "قیمت",
  "sale": "سیل",
  "buy": "خریدیں",
  "sell": "بیچیں",
  "customer": "گاہک",
  "money": "پیسے",
  "payment": "ادائیگی",
  "success": "کامیابی",
  "failure": "ناکامی",
  "competition": "مقابلہ",
  "advertisement": "اشتہار",

  // Social
  "people": "لوگ",
  "friend": "دوست",
  "family": "خاندان",
  "community": "برادری",
  "culture": "ثقافت",
  "society": "معاشرہ",
  "relationship": "تعلق",
  "communication": "مواصلات",
  "meeting": "ملاقات",
  "event": "تقریب",

  // Education
  "education": "تعلیم",
  "school": "اسکول",
  "college": "کالج",
  "university": "یونیورسٹی",
  "student": "طالب علم",
  "teacher": "استاد",
  "study": "مطالعہ",
  "research": "تحقیق",
  "exam": "امتحان",
  "result": "نتیجہ",

  // Verbs
  "learn": "سیکھیں",
  "work": "کام",
  "create": "تخلیق کریں",
  "build": "بنائیں",
  "start": "شروع کریں",
  "stop": "روکیں",
  "continue": "جاری رکھیں",
  "improve": "بہتر بنائیں",
  "grow": "بڑھیں",
  "help": "مدد کریں",
  
  // Adjectives
  "good": "اچھا",
  "bad": "برا",
  "new": "نیا",
  "old": "پرانا",
  "big": "بڑا",
  "small": "چھوٹا",
  "easy": "آسان",
  "difficult": "مشکل",
  "important": "اہم",
  "interesting": "دلچسپ",

  "handbook": "رہنما کتاب",
  "working": "کام کرنا",
  "rules": "قوانین",
  "programme": "پروگرام",
  "assignments": "اسائنمنٹس",
  "project": "منصوبہ",
  "submission": "جمع کروانا",
  "grading": "درجہ بندی",
  "support": "مدد",
  "kick-off": "آغاز",
  "setup": "ترتیب دینا",
  "workflow": "ورک فلو",
  "started": "شروع کیا",
  "creating": "بنانا",
  "onboarding": "شروعاتی مرحلہ",
  "checklist": "چیک لسٹ",
  "fundamentals": "بنیادی اصول",
  "router": "راؤٹر",
  "server": "سرور",
  "components": "اجزاء",
  "ui": "یوزر انٹرفیس",
  "theming": "تھیم بندی",
  "styling": "سجاوٹ",
  "accessibility": "رسائی",
  "testing": "جانچ",
  "review": "جائزہ",
  "demo": "ڈیمو",
  "quote": "اقتباس",
  "generator": "جنریٹر",
  "intro": "تعارف",
  "webhooks": "ویب ہکس",
  "agents": "ایجنٹس",
  "integration": "انضمام",
  "crud": "کریئیٹ، ریڈ، اپڈیٹ، ڈیلیٹ",
  "ci/cd": "مسلسل انضمام / مسلسل تعیناتی",
  "actions": "اعمال",
  "due": "آخری تاریخ",
  "sprint": "تیز کام",
  "wireframes": "وائر فریمز",
  "backend": "بیک اینڈ",
  "db": "ڈیٹا بیس",
  "milestone": "اہم مرحلہ",
  "pushed": "دھکیلا گیا / اپ لوڈ کیا گیا",
  "frontend": "فرنٹ اینڈ",
  "logic": "منطق",
  "polish": "چمکانا / بہتر بنانا",
  "responsiveness": "جوابی صلاحیت",
  "bug-fixing": "خرابی دور کرنا",
  "tweaks": "تبدیلیاں",
  "public": "عوامی",
  "live": "براہ راست",
  "qa": "کوالٹی اشورنس",
  "optimization": "بہتری",
  "docs": "دستاویزات",
  "walkthrough": "وضاحت",
  "final": "حتمی",
  "building": "تعمیر کرنا",
  "intelligent": "ذہین",
  "solutions": "حل",
  "transformation": "تبدیلی",
};

export function translateToUrdu(text: string): string {
  return text
    .split(' ')
    .map(word => dictionary[word] || word)
    .join(' ');
}
